### ISSUE TITLE
[Proposal] Add package.json

### ISSUE THREAD

**Issue by hardcoding** [Xn1ch1/js-dialog-box#2]
Hi Xn1ch1,

"npm install Xn1ch1/js-dialog-box" currently results in an error: "npm ERR! premature close".
This seems to be, because there is no package.json in the repository.

Would you like your project to be extended by this file / usage possibility?

Greets,
Johnny

**Comment by Xn1ch1** [comment]
Yes, that would be good thank you. There is still much work to be done on this so all good suggestions are welcome
